// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TimeBooking.Data.Models
{
    [Keyless]
    public partial class ActiveClient
    {
        public Guid? KundeId { get; set; }
        [StringLength(100)]
        [Unicode(false)]
        public string KundeName { get; set; }
        public bool? Intern { get; set; }
        public bool? Aktiv { get; set; }
        [StringLength(1000)]
        [Unicode(false)]
        public string Adresse { get; set; }
    }
}