// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TimeBooking.Data.Models
{
    [Keyless]
    public partial class AktiveProjekte
    {
        public Guid? ProjektId { get; set; }
        public Guid? KundeId { get; set; }
        [StringLength(100)]
        [Unicode(false)]
        public string ProjektNummer { get; set; }
        [StringLength(100)]
        [Unicode(false)]
        public string ProjektBezeichnung { get; set; }
        public bool? Aktiv { get; set; }
        [Column(TypeName = "numeric(18, 2)")]
        public decimal? Gesamtkosten { get; set; }
        public bool? Pauschal { get; set; }
        [StringLength(100)]
        [Unicode(false)]
        public string Vertragsdauer { get; set; }
    }
}