// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TimeBooking.Data.Models
{
    [Table("Arbeitszeit")]
    [Index("Jahr", "Monat", Name = "UK_Arbeitszeit", IsUnique = true)]
    public partial class Arbeitszeit
    {
        [Key]
        public Guid ArbeitszeitId { get; set; }
        public int Jahr { get; set; }
        public int Monat { get; set; }
        [Column("Arbeitszeit", TypeName = "numeric(18, 2)")]
        public decimal Arbeitszeit1 { get; set; }
        [Column(TypeName = "numeric(18, 2)")]
        public decimal Tagesarbeitszeit { get; set; }
    }
}