// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TimeBooking.Data.Models
{
    [Table("ArbeitszeitReduktion")]
    [Index("Datum", Name = "UK_ArbeitszeitReduktion", IsUnique = true)]
    public partial class ArbeitszeitReduktion
    {
        [Key]
        public Guid ReduktionId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Datum { get; set; }
        [Column(TypeName = "numeric(3, 2)")]
        public decimal Reduktion { get; set; }
    }
}