// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TimeBooking.Data.Models
{
    [Table("Booking")]
    public partial class Booking
    {
        [Key]
        public Guid BookingId { get; set; }
        public Guid ProcessId { get; set; }
        public Guid EmployeeId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime BookingDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime BookingFrom { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime BookingTill { get; set; }
        [Required]
        [StringLength(100)]
        [Unicode(false)]
        public string BookingComment { get; set; }
        public bool Hours { get; set; }

        [ForeignKey("EmployeeId")]
        [InverseProperty("Bookings")]
        public virtual Employee Employee { get; set; }
        [ForeignKey("ProcessId")]
        [InverseProperty("Bookings")]
        public virtual Process Process { get; set; }
    }
}