// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TimeBooking.Data.Models
{
    [Table("EmployeeBalance")]
    [Index("EmployeeId", "Year", "Month", Name = "UK_EmployeeBalance", IsUnique = true)]
    public partial class EmployeeBalance
    {
        [Key]
        public Guid EmployeeBalanceId { get; set; }
        public Guid EmployeeId { get; set; }
        public int Year { get; set; }
        public int Month { get; set; }
        [Column(TypeName = "numeric(18, 2)")]
        public decimal HourBalance { get; set; }
        [Column(TypeName = "numeric(18, 2)")]
        public decimal VacationBalance { get; set; }
        [Column(TypeName = "numeric(18, 2)")]
        public decimal Target { get; set; }
        [Column(TypeName = "numeric(18, 2)")]
        public decimal Actual { get; set; }
    }
}