// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using Telerik.SvgIcons;

namespace TimeBooking.Data.Models
{
    [Table("Employees")]
    public partial class Employee
    {
        public Employee()
        {
            Bookings = new HashSet<Booking>();
            VacationWorkloads = new HashSet<VacationWorkload>();
            Expenses = new HashSet<Expense>();
        }

        [Key]
        public Guid EmployeeId { get; set; }
        [Required]
        [StringLength(100)]
        [Unicode(false)]
        public string EmployeeLastName { get; set; }
        [Required]
        [StringLength(100)]
        [Unicode(false)]
        public string EmployeeFirstName { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Entry { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Exit { get; set; }

        [InverseProperty("Employee")]
        public virtual ICollection<Booking> Bookings { get; set; }
        [InverseProperty("Employee")]
        public virtual ICollection<VacationWorkload> VacationWorkloads { get; set; }
        [InverseProperty("Employee")]
        public virtual ICollection<Expense> Expenses { get; set; }
    }
}