// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TimeBooking.Data.Models
{
    [Table("FerienArbeitspensum")]
    [Index("MitarbeiterId", "GueltigAb", Name = "UK_FerienArbeitspensum", IsUnique = true)]
    public partial class FerienArbeitspensum
    {
        [Key]
        public Guid FerienArbeitspensumId { get; set; }
        public Guid MitarbeiterId { get; set; }
        [Column(TypeName = "numeric(3, 0)")]
        public decimal FerienProJahr { get; set; }
        [Column(TypeName = "numeric(3, 0)")]
        public decimal Arbeitspensum { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime GueltigAb { get; set; }
        [Required]
        public bool? Montag { get; set; }
        [Required]
        public bool? Dienstag { get; set; }
        [Required]
        public bool? Mittwoch { get; set; }
        [Required]
        public bool? Donnerstag { get; set; }
        [Required]
        public bool? Freitag { get; set; }

        [ForeignKey("MitarbeiterId")]
        [InverseProperty("FerienArbeitspensums")]
        public virtual Mitarbeiter Mitarbeiter { get; set; }
    }
}