// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TimeBooking.Data.Models
{
    [Keyless]
    public partial class InactiveProcesses
    {
        public Guid ProcessId { get; set; }
        public Guid ProjectId { get; set; }
        [Required]
        [StringLength(100)]
        [Unicode(false)]
        public string ProcessName { get; set; }
        public bool? IsActive { get; set; }
        public bool IsVacation { get; set; }
        [Column(TypeName = "numeric(18, 2)")]
        public decimal HourlyRate { get; set; }
    }
}