// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TimeBooking.Data.Models
{
    [Keyless]
    public partial class InactiveClient
    {
        public Guid ClientId { get; set; }
        [Required]
        [StringLength(100)]
        [Unicode(false)]
        public string ClientName { get; set; }
        public bool IsInternal { get; set; }
        public bool? IsActive { get; set; }
        [StringLength(1000)]
        [Unicode(false)]
        public string Address { get; set; }
    }
}