// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TimeBooking.Data.Models
{
    [Table("Kunde")]
    public partial class Kunde
    {
        public Kunde()
        {
            Projekts = new HashSet<Projekt>();
        }

        [Key]
        public Guid KundeId { get; set; }
        [Required]
        [StringLength(100)]
        [Unicode(false)]
        public string KundeName { get; set; }
        public bool Intern { get; set; }
        [Required]
        public bool? Aktiv { get; set; }
        [StringLength(1000)]
        [Unicode(false)]
        public string Adresse { get; set; }

        [InverseProperty("Kunde")]
        public virtual ICollection<Projekt> Projekts { get; set; }
    }
}