// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TimeBooking.Data.Models
{
    [Table("Mitarbeiter")]
    public partial class Mitarbeiter
    {
        public Mitarbeiter()
        {
            Buchungs = new HashSet<Buchung>();
            FerienArbeitspensums = new HashSet<FerienArbeitspensum>();
            Spesens = new HashSet<Spesen>();
        }

        [Key]
        public Guid MitarbeiterId { get; set; }
        [Required]
        [StringLength(100)]
        [Unicode(false)]
        public string MitarbeiterName { get; set; }
        [Required]
        [StringLength(100)]
        [Unicode(false)]
        public string MitarbeiterVorname { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Eintritt { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Austritt { get; set; }

        [InverseProperty("Mitarbeiter")]
        public virtual ICollection<Buchung> Buchungs { get; set; }
        [InverseProperty("Mitarbeiter")]
        public virtual ICollection<FerienArbeitspensum> FerienArbeitspensums { get; set; }
        [InverseProperty("Mitarbeiter")]
        public virtual ICollection<Spesen> Spesens { get; set; }
    }
}