// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TimeBooking.Data.Models
{
    [Table("Processes")]
    public partial class Process
    {
        public Process()
        {
            Bookings = new HashSet<Booking>();
        }

        [Key]
        public Guid ProcessId { get; set; }
        public Guid ProjectId { get; set; }
        [Required]
        [StringLength(100)]
        [Unicode(false)]
        public string ProcessName { get; set; }
        [Required]
        public bool? Active { get; set; }
        public bool Vacation { get; set; }
        [Column(TypeName = "numeric(18, 2)")]
        public decimal HourlyRate { get; set; }
        [Column(TypeName = "numeric(18, 2)")]
        public decimal AmountHours { get; set; }

        [ForeignKey("ProjektId")]
        [InverseProperty("Processes")]
        public virtual Project Project { get; set; }
        [InverseProperty("Process")]
        public virtual ICollection<Booking> Bookings { get; set; }
    }
}