// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TimeBooking.Data.Models
{
    [Table("Projects")]
    public partial class Project
    {
        public Project()
        {
            Processes = new HashSet<Process>();
        }

        [Key]
        public Guid ProjectId { get; set; }
        public Guid ClientId { get; set; }
        [Required]
        [StringLength(100)]
        [Unicode(false)]
        public string ProjectNumber { get; set; }
        [Required]
        [StringLength(100)]
        [Unicode(false)]
        public string ProjectName { get; set; }
        [Required]
        public bool? IsActive { get; set; }
        [Column(TypeName = "numeric(18, 2)")]
        public decimal TotalCosts { get; set; }
        public bool IsFlatRate { get; set; }
        [StringLength(100)]
        [Unicode(false)]
        public string ContractDuration { get; set; }
        public bool VAT { get; set; }

        [ForeignKey("ClientId")]
        [InverseProperty("Projects")]
        public virtual Client Client { get; set; }
        [InverseProperty("Project")]
        public virtual ICollection<Process> Processes { get; set; }
    }
}