// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TimeBooking.Data.Models
{
    [Table("VacationWorkload")]
    [Index("EmployeeId", "ValidFrom", Name = "UK_VacationWorkload", IsUnique = true)]
    public partial class VacationWorkload
    {
        [Key]
        public Guid VacationWorkloadId { get; set; }
        public Guid EmployeeId { get; set; }
        [Column(TypeName = "numeric(3, 0)")]
        public decimal VacationPerYear { get; set; }
        [Column(TypeName = "numeric(3, 0)")]
        public decimal Workload { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime ValidFrom { get; set; }
        [Required]
        public bool? Monday { get; set; }
        [Required]
        public bool? Tuesday { get; set; }
        [Required]
        public bool? Wednesday { get; set; }
        [Required]
        public bool? Thursday { get; set; }
        [Required]
        public bool? Friday { get; set; }

        [ForeignKey("EmployeeId")]
        [InverseProperty("VacationWorkloads")]
        public virtual Employee Employee { get; set; }
    }
}