// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TimeBooking.Data.Models
{
    [Table("WorkloadReduction")]
    [Index("Date", Name = "UK_WorkloadReduction", IsUnique = true)]
    public partial class WorkloadReduction
    {
        [Key]
        public Guid ReductionId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Date { get; set; }
        [Column(TypeName = "numeric(3, 2)")]
        public decimal Reduction { get; set; }
    }
}